export type TripIdeaSeed = {
  id: string;
  name: string;
  region: string;
  emoji: string;
  type: string;
  description: string;
  // Estimated cost for ~4 people for a long weekend
  estimatedCost: number;
  // Approximate distance from each "home" hub in miles
  distanceFromHub: Record<HomeHub, number>;
  tags: string[];
  activities: string[];
  bestSeason: string;
  accent: "sunset" | "amber" | "emerald" | "sky" | "purple" | "pink" | "teal" | "rose";
};

export const HOME_HUBS = [
  "Los Angeles, CA",
  "San Francisco, CA",
  "Seattle, WA",
  "Denver, CO",
  "Chicago, IL",
  "Dallas, TX",
  "New York, NY",
  "Miami, FL",
] as const;

export type HomeHub = (typeof HOME_HUBS)[number];

// Distance is approximate — for filtering, not navigation. Values picked to spread
// nicely across the slider.
export const tripIdeas: TripIdeaSeed[] = [
  {
    id: "yosemite",
    name: "Yosemite National Park",
    region: "California",
    emoji: "🏞️",
    type: "National Park",
    description: "Granite cliffs, waterfalls, and big trees. Hikes for everyone from grandma to the kids.",
    estimatedCost: 1800,
    distanceFromHub: {
      "Los Angeles, CA": 280, "San Francisco, CA": 170, "Seattle, WA": 900,
      "Denver, CO": 1180, "Chicago, IL": 2100, "Dallas, TX": 1700,
      "New York, NY": 2900, "Miami, FL": 3000,
    },
    tags: ["Outdoors", "Family-friendly", "Hikes"],
    activities: ["Mist Trail hike", "Glacier Point sunset", "Tunnel View photo"],
    bestSeason: "May–Sep",
    accent: "emerald",
  },
  {
    id: "joshua-tree",
    name: "Joshua Tree",
    region: "California",
    emoji: "🌵",
    type: "Camping",
    description: "Otherworldly desert, world-class stargazing, easy scrambles for kids.",
    estimatedCost: 700,
    distanceFromHub: {
      "Los Angeles, CA": 130, "San Francisco, CA": 480, "Seattle, WA": 1200,
      "Denver, CO": 950, "Chicago, IL": 1850, "Dallas, TX": 1300,
      "New York, NY": 2700, "Miami, FL": 2600,
    },
    tags: ["Outdoors", "Stars", "Cheap"],
    activities: ["Hidden Valley loop", "Stargazing night", "Cholla garden"],
    bestSeason: "Oct–Apr",
    accent: "amber",
  },
  {
    id: "tahoe",
    name: "Lake Tahoe",
    region: "California / Nevada",
    emoji: "🌲",
    type: "Cabin",
    description: "Crystal-clear lake, alpine forests, year-round play. Easy cabin life.",
    estimatedCost: 1400,
    distanceFromHub: {
      "Los Angeles, CA": 470, "San Francisco, CA": 200, "Seattle, WA": 760,
      "Denver, CO": 1010, "Chicago, IL": 1980, "Dallas, TX": 1620,
      "New York, NY": 2820, "Miami, FL": 2950,
    },
    tags: ["Lake", "Cabin", "Family-friendly"],
    activities: ["Boat day", "Emerald Bay viewpoint", "Lakefront BBQ"],
    bestSeason: "Jun–Sep, Dec–Mar",
    accent: "sky",
  },
  {
    id: "sequoia",
    name: "Sequoia National Park",
    region: "California",
    emoji: "🌲",
    type: "National Park",
    description: "The biggest trees on Earth. Easy walks, jaw-dropping scale.",
    estimatedCost: 1300,
    distanceFromHub: {
      "Los Angeles, CA": 220, "San Francisco, CA": 280, "Seattle, WA": 1010,
      "Denver, CO": 1140, "Chicago, IL": 2050, "Dallas, TX": 1620,
      "New York, NY": 2860, "Miami, FL": 2950,
    },
    tags: ["Outdoors", "Senior-friendly", "Family-friendly"],
    activities: ["General Sherman Tree", "Moro Rock", "Crescent Meadow loop"],
    bestSeason: "May–Oct",
    accent: "emerald",
  },
  {
    id: "san-diego",
    name: "San Diego",
    region: "California",
    emoji: "🏖️",
    type: "Beach",
    description: "Beach town energy. Tacos, sea lions, easy strolls. Great for big groups.",
    estimatedCost: 1600,
    distanceFromHub: {
      "Los Angeles, CA": 120, "San Francisco, CA": 500, "Seattle, WA": 1250,
      "Denver, CO": 1100, "Chicago, IL": 2080, "Dallas, TX": 1370,
      "New York, NY": 2770, "Miami, FL": 2580,
    },
    tags: ["Beach", "Food", "Family-friendly"],
    activities: ["La Jolla Cove", "Coronado bike day", "Old Town tacos"],
    bestSeason: "Mar–Oct",
    accent: "sunset",
  },
  {
    id: "portland",
    name: "Portland",
    region: "Oregon",
    emoji: "🌧️",
    type: "City",
    description: "Food carts, bookstores, easy waterfalls within an hour. Cozy and low-key.",
    estimatedCost: 1500,
    distanceFromHub: {
      "Los Angeles, CA": 960, "San Francisco, CA": 640, "Seattle, WA": 175,
      "Denver, CO": 1240, "Chicago, IL": 2120, "Dallas, TX": 2080,
      "New York, NY": 2900, "Miami, FL": 3300,
    },
    tags: ["City", "Food", "Rainy-day"],
    activities: ["Multnomah Falls", "Powell's Books", "Food cart tour"],
    bestSeason: "Jun–Sep",
    accent: "teal",
  },
  {
    id: "nashville",
    name: "Nashville",
    region: "Tennessee",
    emoji: "🎸",
    type: "City",
    description: "Live music every night, good BBQ, hot chicken pilgrimage. Easy for grandparents too.",
    estimatedCost: 1700,
    distanceFromHub: {
      "Los Angeles, CA": 2100, "San Francisco, CA": 2400, "Seattle, WA": 2380,
      "Denver, CO": 1170, "Chicago, IL": 470, "Dallas, TX": 660,
      "New York, NY": 890, "Miami, FL": 910,
    },
    tags: ["Music", "Food", "City"],
    activities: ["Honky tonks on Broadway", "Hot chicken lunch", "Hatch Show Print tour"],
    bestSeason: "Apr–Jun, Sep–Oct",
    accent: "amber",
  },
  {
    id: "savannah",
    name: "Savannah",
    region: "Georgia",
    emoji: "🌳",
    type: "City",
    description: "Spanish moss squares, slow walks, Southern dinners. Romantic and ridiculously charming.",
    estimatedCost: 1500,
    distanceFromHub: {
      "Los Angeles, CA": 2470, "San Francisco, CA": 2700, "Seattle, WA": 2700,
      "Denver, CO": 1670, "Chicago, IL": 950, "Dallas, TX": 1100,
      "New York, NY": 800, "Miami, FL": 480,
    },
    tags: ["Historic", "Food", "Senior-friendly"],
    activities: ["Forsyth Park stroll", "River Street walk", "Mrs. Wilkes lunch"],
    bestSeason: "Mar–May, Oct",
    accent: "rose",
  },
  {
    id: "smoky-mtns",
    name: "Great Smoky Mountains",
    region: "TN/NC",
    emoji: "⛰️",
    type: "National Park",
    description: "Misty ridges, easy walks, charming mountain towns nearby. Free to enter.",
    estimatedCost: 1100,
    distanceFromHub: {
      "Los Angeles, CA": 2200, "San Francisco, CA": 2470, "Seattle, WA": 2440,
      "Denver, CO": 1310, "Chicago, IL": 600, "Dallas, TX": 870,
      "New York, NY": 730, "Miami, FL": 760,
    },
    tags: ["Outdoors", "Cheap", "Family-friendly"],
    activities: ["Cades Cove loop", "Clingmans Dome", "Gatlinburg pancakes"],
    bestSeason: "Apr–Oct",
    accent: "emerald",
  },
  {
    id: "santa-fe",
    name: "Santa Fe",
    region: "New Mexico",
    emoji: "🌶️",
    type: "City",
    description: "Adobe everything, art galleries, and chile on every plate. High desert magic.",
    estimatedCost: 1600,
    distanceFromHub: {
      "Los Angeles, CA": 870, "San Francisco, CA": 1190, "Seattle, WA": 1500,
      "Denver, CO": 390, "Chicago, IL": 1310, "Dallas, TX": 640,
      "New York, NY": 2000, "Miami, FL": 2050,
    },
    tags: ["Art", "Food", "Senior-friendly"],
    activities: ["Canyon Road galleries", "Meow Wolf", "Plaza enchiladas"],
    bestSeason: "Apr–Oct",
    accent: "sunset",
  },
  {
    id: "moab",
    name: "Moab",
    region: "Utah",
    emoji: "🪨",
    type: "Adventure",
    description: "Two national parks at the door — Arches and Canyonlands. Red rock everywhere.",
    estimatedCost: 1500,
    distanceFromHub: {
      "Los Angeles, CA": 700, "San Francisco, CA": 870, "Seattle, WA": 1140,
      "Denver, CO": 360, "Chicago, IL": 1390, "Dallas, TX": 1240,
      "New York, NY": 2100, "Miami, FL": 2390,
    },
    tags: ["Outdoors", "Adventure"],
    activities: ["Delicate Arch hike", "Mesa Arch sunrise", "Colorado River float"],
    bestSeason: "Mar–May, Sep–Nov",
    accent: "rose",
  },
  {
    id: "yellowstone",
    name: "Yellowstone",
    region: "Wyoming",
    emoji: "♨️",
    type: "National Park",
    description: "Geysers, bison, the works. Classic American road trip.",
    estimatedCost: 2200,
    distanceFromHub: {
      "Los Angeles, CA": 950, "San Francisco, CA": 980, "Seattle, WA": 720,
      "Denver, CO": 560, "Chicago, IL": 1370, "Dallas, TX": 1500,
      "New York, NY": 2070, "Miami, FL": 2490,
    },
    tags: ["Outdoors", "Wildlife", "Family-friendly"],
    activities: ["Old Faithful", "Grand Prismatic", "Lamar Valley wildlife drive"],
    bestSeason: "May–Sep",
    accent: "amber",
  },
  {
    id: "outer-banks",
    name: "Outer Banks",
    region: "North Carolina",
    emoji: "🦀",
    type: "Beach",
    description: "Wild beaches, lighthouses, wild horses. The good kind of nothing-to-do.",
    estimatedCost: 1700,
    distanceFromHub: {
      "Los Angeles, CA": 2700, "San Francisco, CA": 2900, "Seattle, WA": 2870,
      "Denver, CO": 1850, "Chicago, IL": 950, "Dallas, TX": 1330,
      "New York, NY": 460, "Miami, FL": 870,
    },
    tags: ["Beach", "Family-friendly"],
    activities: ["Cape Hatteras lighthouse", "Wild horse tour", "Crab boil dinner"],
    bestSeason: "May–Sep",
    accent: "sky",
  },
  {
    id: "asheville",
    name: "Asheville",
    region: "North Carolina",
    emoji: "🍂",
    type: "Mountain Town",
    description: "Blue Ridge views, breweries, leaf-peeping in October. Easy charm.",
    estimatedCost: 1300,
    distanceFromHub: {
      "Los Angeles, CA": 2270, "San Francisco, CA": 2530, "Seattle, WA": 2520,
      "Denver, CO": 1410, "Chicago, IL": 660, "Dallas, TX": 980,
      "New York, NY": 720, "Miami, FL": 750,
    },
    tags: ["Outdoors", "Food", "Senior-friendly"],
    activities: ["Biltmore", "Blue Ridge Parkway drive", "Brewery hop"],
    bestSeason: "Apr–Jun, Sep–Oct",
    accent: "rose",
  },
  {
    id: "boston",
    name: "Boston",
    region: "Massachusetts",
    emoji: "🦞",
    type: "City",
    description: "Cobblestones, history, Sunday lobster rolls. Walkable for everyone.",
    estimatedCost: 1900,
    distanceFromHub: {
      "Los Angeles, CA": 3000, "San Francisco, CA": 3100, "Seattle, WA": 3060,
      "Denver, CO": 2000, "Chicago, IL": 1000, "Dallas, TX": 1750,
      "New York, NY": 220, "Miami, FL": 1500,
    },
    tags: ["City", "Historic", "Food"],
    activities: ["Freedom Trail", "Fenway tour", "North End cannolis"],
    bestSeason: "May–Oct",
    accent: "sunset",
  },
  {
    id: "key-west",
    name: "Key West",
    region: "Florida",
    emoji: "🌴",
    type: "Beach",
    description: "Cuban coffee, sunset celebrations, no-shoes attitude.",
    estimatedCost: 2000,
    distanceFromHub: {
      "Los Angeles, CA": 2750, "San Francisco, CA": 3100, "Seattle, WA": 3300,
      "Denver, CO": 2100, "Chicago, IL": 1500, "Dallas, TX": 1430,
      "New York, NY": 1300, "Miami, FL": 165,
    },
    tags: ["Beach", "Food", "Relaxing"],
    activities: ["Mallory Square sunset", "Conch fritters", "Snorkeling at Dry Tortugas"],
    bestSeason: "Nov–Apr",
    accent: "teal",
  },
  {
    id: "boundary-waters",
    name: "Boundary Waters",
    region: "Minnesota",
    emoji: "🛶",
    type: "Camping",
    description: "Canoe through a million lakes. No roads, no Wi-Fi, no problem.",
    estimatedCost: 1100,
    distanceFromHub: {
      "Los Angeles, CA": 2050, "San Francisco, CA": 2050, "Seattle, WA": 1700,
      "Denver, CO": 1100, "Chicago, IL": 510, "Dallas, TX": 1240,
      "New York, NY": 1380, "Miami, FL": 1900,
    },
    tags: ["Outdoors", "Adventure", "Cheap"],
    activities: ["Canoe portage", "Lakeside camping", "Loon-spotting"],
    bestSeason: "Jun–Sep",
    accent: "sky",
  },
  {
    id: "charleston",
    name: "Charleston",
    region: "South Carolina",
    emoji: "🦀",
    type: "City",
    description: "Pastel rowhouses, slow porches, the best shrimp & grits. Pure South.",
    estimatedCost: 1700,
    distanceFromHub: {
      "Los Angeles, CA": 2400, "San Francisco, CA": 2700, "Seattle, WA": 2750,
      "Denver, CO": 1670, "Chicago, IL": 880, "Dallas, TX": 1090,
      "New York, NY": 770, "Miami, FL": 530,
    },
    tags: ["Historic", "Food", "Senior-friendly"],
    activities: ["Rainbow Row walk", "Boone Hall tour", "Shrimp & grits dinner"],
    bestSeason: "Mar–May, Sep–Nov",
    accent: "rose",
  },
  {
    id: "san-juan-pr",
    name: "San Juan",
    region: "Puerto Rico",
    emoji: "🌺",
    type: "International",
    description: "No passport needed, all the warmth. Old Town charm + beach in one.",
    estimatedCost: 2400,
    distanceFromHub: {
      "Los Angeles, CA": 3500, "San Francisco, CA": 3700, "Seattle, WA": 3900,
      "Denver, CO": 2700, "Chicago, IL": 2100, "Dallas, TX": 2200,
      "New York, NY": 1600, "Miami, FL": 1050,
    },
    tags: ["Beach", "International", "Food"],
    activities: ["Old San Juan walk", "El Yunque rainforest", "Mofongo dinner"],
    bestSeason: "Dec–Apr",
    accent: "pink",
  },
  {
    id: "glacier",
    name: "Glacier National Park",
    region: "Montana",
    emoji: "🏔️",
    type: "National Park",
    description: "Going-to-the-Sun Road. Mountain lakes you can't believe are real.",
    estimatedCost: 1900,
    distanceFromHub: {
      "Los Angeles, CA": 1300, "San Francisco, CA": 1200, "Seattle, WA": 540,
      "Denver, CO": 1000, "Chicago, IL": 1530, "Dallas, TX": 1740,
      "New York, NY": 2200, "Miami, FL": 2730,
    },
    tags: ["Outdoors", "Adventure"],
    activities: ["Going-to-the-Sun drive", "Hidden Lake hike", "Lake McDonald paddle"],
    bestSeason: "Jul–Sep",
    accent: "emerald",
  },
  {
    id: "weekend-camp",
    name: "Local State Park Camp",
    region: "Anywhere",
    emoji: "🏕️",
    type: "Camping",
    description: "Cheap and easy weekend close to home. Every state has a stunner within 2 hours.",
    estimatedCost: 250,
    distanceFromHub: {
      "Los Angeles, CA": 90, "San Francisco, CA": 80, "Seattle, WA": 75,
      "Denver, CO": 60, "Chicago, IL": 100, "Dallas, TX": 90,
      "New York, NY": 110, "Miami, FL": 100,
    },
    tags: ["Outdoors", "Cheap", "Quick"],
    activities: ["Tent setup", "Campfire dinner", "Morning trail walk"],
    bestSeason: "Apr–Oct",
    accent: "amber",
  },
  {
    id: "day-trip-beach",
    name: "Day Trip Beach Run",
    region: "Anywhere",
    emoji: "🏝️",
    type: "Day Trip",
    description: "No overnight, just sand. Pack a cooler, leave by 8 AM.",
    estimatedCost: 150,
    distanceFromHub: {
      "Los Angeles, CA": 30, "San Francisco, CA": 25, "Seattle, WA": 60,
      "Denver, CO": 999, "Chicago, IL": 70, "Dallas, TX": 240,
      "New York, NY": 60, "Miami, FL": 15,
    },
    tags: ["Beach", "Cheap", "Quick"],
    activities: ["Beach blanket lunch", "Body surfing", "Sunset drive home"],
    bestSeason: "Year-round",
    accent: "sky",
  },
];
